/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppSpoofUsersImport } from './routes/_app/spoof/users'
import { Route as AppItemItemIdImport } from './routes/_app/item/$itemId'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppSpoofUsersRoute = AppSpoofUsersImport.update({
  id: '/spoof/users',
  path: '/spoof/users',
  getParentRoute: () => AppRoute,
} as any)

const AppItemItemIdRoute = AppItemItemIdImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/item/$itemId': {
      id: '/_app/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof AppItemItemIdImport
      parentRoute: typeof AppImport
    }
    '/_app/spoof/users': {
      id: '/_app/spoof/users'
      path: '/spoof/users'
      fullPath: '/spoof/users'
      preLoaderRoute: typeof AppSpoofUsersImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppItemItemIdRoute: typeof AppItemItemIdRoute
  AppSpoofUsersRoute: typeof AppSpoofUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppItemItemIdRoute: AppItemItemIdRoute,
  AppSpoofUsersRoute: AppSpoofUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexRoute
  '/item/$itemId': typeof AppItemItemIdRoute
  '/spoof/users': typeof AppSpoofUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/item/$itemId': typeof AppItemItemIdRoute
  '/spoof/users': typeof AppSpoofUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/item/$itemId': typeof AppItemItemIdRoute
  '/_app/spoof/users': typeof AppSpoofUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/item/$itemId' | '/spoof/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/item/$itemId' | '/spoof/users'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/item/$itemId'
    | '/_app/spoof/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/item/$itemId",
        "/_app/spoof/users"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/item/$itemId": {
      "filePath": "_app/item/$itemId.tsx",
      "parent": "/_app"
    },
    "/_app/spoof/users": {
      "filePath": "_app/spoof/users.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
